server:
  port: 8085
  application:
    name: small-shop

### For DB ###
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/${DB_NAME:small_shop}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:rootroot}
  flyway:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/${DB_NAME:small_shop}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:rootroot}
    baseline-on-migrate: true
  db:
    hostname: ${DB_HOSTNAME:localhost}
    port: ${DB_PORT:5432}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:rootroot}
    name: ${DB_NAME:small_shop}
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

