CREATE TABLE IF NOT EXISTS base_entity
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    serial_number VARCHAR(255),
    manufacturer  VARCHAR(255),
    price         DOUBLE PRECISION,
    stock_balance BIGINT,
    CONSTRAINT pk_baseentity PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS desktop_computer
(
    id          BIGINT NOT NULL,
    form_factor INTEGER,
    CONSTRAINT pk_desktopcomputer PRIMARY KEY (id)
);

ALTER TABLE desktop_computer
    ADD CONSTRAINT FK_DESKTOPCOMPUTER_ON_ID FOREIGN KEY (id) REFERENCES base_entity (id);

CREATE TABLE IF NOT EXISTS hard_drive
(
    id       BIGINT NOT NULL,
    capacity INTEGER,
    CONSTRAINT pk_harddrive PRIMARY KEY (id)
);

ALTER TABLE hard_drive
    ADD CONSTRAINT FK_HARDDRIVE_ON_ID FOREIGN KEY (id) REFERENCES base_entity (id);

CREATE TABLE IF NOT EXISTS laptop
(
    id   BIGINT NOT NULL,
    size INTEGER,
    CONSTRAINT pk_laptop PRIMARY KEY (id)
);

ALTER TABLE laptop
    ADD CONSTRAINT FK_LAPTOP_ON_ID FOREIGN KEY (id) REFERENCES base_entity (id);

CREATE TABLE IF NOT EXISTS monitor
(
    id          BIGINT NOT NULL,
    screen_size DOUBLE PRECISION,
    CONSTRAINT pk_monitor PRIMARY KEY (id)
);

ALTER TABLE monitor
    ADD CONSTRAINT FK_MONITOR_ON_ID FOREIGN KEY (id) REFERENCES base_entity (id);