CREATE TABLE IF NOT EXISTS desktop_computers
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dtype         VARCHAR(31),
    serial_number INTEGER,
    manufacturer  VARCHAR(255),
    price         DOUBLE PRECISION,
    stock_balance BIGINT,
    form_factor   INTEGER,
    CONSTRAINT pk_baseentity PRIMARY KEY (id)
);